### ISSUE TITLE
Example failed

### ISSUE THREAD

**Issue by liangshuang1993** [matt-baugh/pytorch-poisson-image-editing#1]
I run the example in examples.ipynb. But got an error:
**ValueError: Floating point image RGB values must be in the 0..1 range.**. Max value of result if 1.2374748. 

Could you fix this error, thanks!

**Comment by matt-baugh** [comment]
I just tried re-cloning + running the examples and it seemed to work fine, could you send a screenshot of the error? Also which part of the notebook is causing it?

**Comment by liangshuang1993** [comment]
> I just tried re-cloning + running the examples and it seemed to work fine, could you send a screenshot of the error? Also which part of the notebook is causing it?

Thanks for your reply.
I used plt.imsave instead of imshow, which causes the error. After clip the value to [0, 1], I can get the same result.
But the max value of res is still bigger than 1 in this example. Is this a bug or I can just ignore this?
![image](https://user-images.githubusercontent.com/7533616/216217777-30a2bef0-00a9-4ed4-8cb0-7154aea7e723.png)

**Comment by matt-baugh** [comment]
This isn't a bug, but it is worth being careful of. Let me try to explain what's happening (I'll use a 1D example as it's easier to visualise):
![image](https://user-images.githubusercontent.com/52428833/216316255-e118b63d-871c-4ccc-b9aa-f5808cdb68dc.png)
Here both our source and target images start in the normal intensity range, but as Poisson image editing seamlessly blends the source patch into the context of the target image, it results in some of the values going outside of the 0-1 range.
In the example image, this happens because the mug is quite a light colour, so the intensity values are already pretty high. The brick texture then includes some parts where a dark texture (the mortar) is next to a light texture (some of the bricks) so the image gradient is also quite high. Blending these higher gradients on top of the already high intensities of the beige mug results in values that exceed the 0-1 image range.
As pie-torch is intended to be independent of the application domain it doesn't make any assumptions about what the range of the intensity values should be, but I would recommend that if you want to use it fro normal images such as this then you should clip the values to 0-1 after the blending operation.
Let me know if any of that doesn't make sense and I can have another go at explaining things better :)
