### ISSUE TITLE
Abound bounderies conditions for blending

### ISSUE THREAD

**Issue by conti3000** [matt-baugh/pytorch-poisson-image-editing#5]
If having for instance a source of shape  [3, 175, 480] and target of shape [3, 175, 480], if the corner coordinates are for instance [72, 126 ] the blending failing, I've tried modifyin the code to: ```target_slices = [slice(corner_dict[i], min(corner_dict[i] + s_s, target.shape[i])) if i in chosen_dimensions else slice(None) for i, s_s in enumerate(source.shape)]; target = target[tuple(target_slices)] ```    but I still get the error:  
```
source_grads = [torch.where(torch.ge(torch.abs(t_g), torch.abs(s_g)), t_g, s_g)
RuntimeError: The size of tensor a (362) must match the size of tensor b (488) at non-singleton dimension 2
```

**Comment by matt-baugh** [comment]
Which function are you calling to get this error? From the code snippet it looks like one of the torch implementations, is it `blend` or `blend_wide`?
Also I'm not sure which line you have edited as I don't have a variable called `target_slices`.
It would also be helpful to know what your overall aim is. From what you've said it sounds like, because the source patch is the same size as the target, positioning it at (72,126) means that it doesn't fit inside the target.
Visually, in line 45 of the `blend` function, it crops the image to only the affected area (where we want to do the blending), which starts at corner_coord and normally has the same shape as the source patch. But in your case, the source patch doesn't fit inside the target when positioned here, so only the blue area (in the image below) can be affected. But then as the blue area is smaller than the source patch, it fails.
![image](https://github.com/matt-baugh/pytorch-poisson-image-editing/assets/52428833/79cf1c5a-739f-4300-9373-32b9f4136f13)

If that is your situation, I don't think changing the blend function is the solution as what would the correct behaviour be? You're blending the source with nothing (outside the target's boundaries).
Possible solutions would be:
- crop the source image before calling blend, so it fits inside the target when at the desired location:
- pad the target image before calling blend, so the big source image can fit inside
- only position the source at locations where it fits in the target (so here as they are the same size it can only be blended at (0, 0)
Let me know if I've misunderstood something if your problem is something different I'd be happy to investigate more and find a solution.

**Comment by conti3000** [comment]
I'm just using the ``blend`` function  I think cropping before the mask and the source might be a better idea instead of trying to modify the funcion, thanks
